#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS := ../esplay-hal
PROJECT_NAME := esplay-smsplusgx

include $(IDF_PATH)/make/project.mk
