#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS := $(ESPLAY_SDK)/esplay-components/
PROJECT_NAME := esplay-gnuboy

include $(IDF_PATH)/make/project.mk

